guests = ['Hailey Little', 'Lexi Belle', 'Chloe Foster']
print(guests[0], "- I would like to invite you to dinner.")
print(guests[1], "- I would like to invite you to dinner.")
print(guests[2], "- I would like to invite you to dinner.")
print("\n" + '*'*8)
print('\n', guests[1], 'can no longer make it.')
guests[1] = 'Elsa Jean'
print("\n" + '*'*8)
print(guests[0], "- I would like to invite you to dinner.")
print(guests[1], "- I would like to invite you to dinner.")
print(guests[2], "- I would like to invite you to dinner.")
print("\n" + '*'*8)
guests.insert(0, 'Lily Rader')
guests.insert(3, 'Italia Ricci')
guests.append('Alaina Dawson')
print(guests[0], "- I would like to invite you to dinner.")
print(guests[1], "- I would like to invite you to dinner.")
print(guests[2], "- I would like to invite you to dinner.")
print(guests[3], "- I would like to invite you to dinner.")
print(guests[4], "- I would like to invite you to dinner.")
print(guests[5], "- I would like to invite you to dinner.")
