locations = ['London', 'Paris', 'Rome', 'New York', 'Peckham']
print(locations)
print(sorted(locations))
print(locations)
print(sorted(locations, reverse=True))
print(locations)
locations.reverse()
print(locations)
locations.reverse()
print(locations)

locations.sort()
print(locations)
locations.sort(reverse=True)
print(locations)